def main():
    print("This function will calculate the yeild of any investment")
    print()
    x=(float(input("What is your initial investment?:")))
    print()
    y=(float(input("What is your interest rate(as a decimal point)?:")))
    print()
    w=(float(input("How many times per year is the interested calculated?:")))
    print()
    z=(float(input("How many years are you expecting accrue interest?:")))
    interest= (x*(1+(y/w))**(w*z))
    interest=round(interest,2)
    print("You will yield ",interest)
main()
